name: givemymenu deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Source the NVM configuration to load npm and Node.js from NVM
          export NVM_DIR="/home/givemymenu/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 22.15.0

          # Now check if npm is available
          which npm
          which pm2

          # Navigate to your app's path and deploy
          cd ${{ secrets.SERVER_PATH }}
          git pull origin main
          npm install
          npm run build
          pm2 restart givemymenu
